### ISSUE TITLE
Possibility of being able to customize filepicker ui

### ISSUE THREAD

**Issue by gabbe-swe** [datadirr/file_picker_pro#1]
Hello, the plugin is very complete, but there would be the possibility of being able to change the icons in filepicker (camera, gallery, file, view etc) and being able to customize with a filepicker ui button.

thank you

**Comment by datadirr** [comment]
Hi,

Yes you can make your own ui and implement file_picker_pro functions like Files.cameraPicker, Files.imagePicker and Files.filePicker.

For more information, Please visit https://pub.dev/packages/file_picker_pro#example
