### ISSUE TITLE
Update dependency: image_picker and file_picker_pro

### ISSUE THREAD

**Issue by VersaDesenvolvimento** [datadirr/file_picker_pro#3]
Hi,

When i try install "flutter pub add file_picker_pro", i got this message:

Because file_picker_pro >=1.3.0 <1.4.0 depends on image_picker ^0.8.7+5 and file_picker_pro <1.3.0 depends on image_picker ^0.8.7+3, file_picker_pro <1.4.0 requires image_picker ^0.8.7+3.
And because file_picker_pro >=1.4.0 <1.5.0 depends on image_picker ^0.8.9, file_picker_pro <1.5.0 requires image_picker ^0.8.7+3.
And because file_picker_pro >=1.5.0 depends on file_picker ^5.3.3 and XXXXXXX depends on file_picker ^6.1.1, every version of file_picker_pro requires image_picker ^0.8.7+3.

So,
I can't install file_picker_pro, because my project use "image_picker: ^1.0.7" and "  file_picker: ^6.1.1"

Could you please update 
Could you, please , update the "image_picker: ^1.0.7" and "  file_picker: ^6.1.1" dependencies?

Thanks in advance

**Comment by datadirr** [comment]
okay, I will try to update

**Comment by datadirr** [comment]
file_picker_pro: ^1.6.0

Okay done, now use this version
